### ISSUE TITLE
Feat songs

### ISSUE THREAD

**Issue by iKASRA-H** [mhshahin/RJ-Downloader#4]
There is a bug in the rj_downloader code that it can't download the songs that they have (feat)

**Comment by mhshahin** [comment]
Dear @iKASRA-H, I'm so sorry that I didn't check this issue sooner. Unfortunately, I was so busy that I completely forgot to check the issue that you've opened while ago on this repository. It seems that you've created your own version of this simple script of mine, and I'm so happy for you that you have managed to fix this issue on your own project.

**Comment by iKASRA-H** [comment]
I've solved it myself

**Comment by iKASRA-H** [comment]
You should put \ before parenthesis I've solved it in a telegram bot
